# Introduction to Data Frames

- A data frames represent a tablear data (table)
- Contains rows and colums
- By colums are also referred by their index(0 to n-1)
- And colums are also referred by their index
- Rows are axis=0 (x-axis) and colums are at axis(y-axis)

In [4]:
# imports
import numpy as np
import pandas as pd

In [29]:
data = {
    'city':['hyd','del','mum','che','kol'],
    'state':['telanagana','delhi','maharastra','tamilnadu','west bengal'],
    'population':[1500000, 1800000, 1400000, 16000000, 1200000]
}

In [30]:
pd.DataFrame(data)

  city        state  population
0  hyd   telanagana     1500000
1  del        delhi     1800000
2  mum   maharastra     1400000
3  che    tamilnadu    16000000
4  kol  west bengal     1200000

In [7]:
customer_visits = np.random.randint(10, 20,(3,5))
customer_visits

array([[13, 10, 18, 15, 16],
       [11, 10, 10, 14, 13],
       [18, 15, 14, 16, 15]], dtype=int32)

In [8]:
pd.DataFrame(customer_visits)

    0   1   2   3   4
0  13  10  18  15  16
1  11  10  10  14  13
2  18  15  14  16  15

In [9]:
pd.DataFrame(customer_visits,
             index=['morning','afternoon','evening'],
             columns=['mon','tue','wed','thu','fri'])

           mon  tue  wed  thu  fri
morning     13   10   18   15   16
afternoon   11   10   10   14   13
evening     18   15   14   16   15

### Loading files

``` python 
# pandas to functions to load files
read_csv() # for csv files
read_json() # for json files
read_excel() # for excel file
read_sql_query # for sql files