In [92]:
# import
import numpy as np
import pandas as pd

## SORTING

In [93]:
nba

               Name                 Team Position  Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG   9/26/96   1445697
1    Christian Wood      Detroit Pistons       PF   9/27/95   1645357
2     PJ Washington    Charlotte Hornets       PF   8/23/98   3831840
3      Derrick Rose      Detroit Pistons       PG   10/4/88   7317074
4     Marial Shayok   Philadelphia 76ers        G   7/26/95     79568
..              ...                  ...      ...       ...       ...
445   Austin Rivers      Houston Rockets       PG    8/1/92   2174310
446     Harry Giles     Sacramento Kings       PF   4/22/98   2578800
447     Robin Lopez      Milwaukee Bucks        C    4/1/88   4767000
448   Collin Sexton  Cleveland Cavaliers       PG    1/4/99   4764960
449     Ricky Rubio         Phoenix Suns       PG  10/21/90  16200000

[450 rows x 5 columns]

In [94]:
nba = pd.read_csv("nba.csv")
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      450 non-null    object
 1   Team      450 non-null    object
 2   Position  450 non-null    object
 3   Birthday  450 non-null    object
 4   Salary    450 non-null    int64
dtypes: int64(1), object(4)
memory usage: 17.7+ KB

In [124]:
nba = pd.read_csv("nba.csv", parse_dates=["Birthday"])
nba

C:\Users\vibhu\AppData\Local\Temp\ipykernel_6352\2377021467.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  nba = pd.read_csv("nba.csv", parse_dates=["Birthday"])

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [125]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      450 non-null    object
 1   Team      450 non-null    object
 2   Position  450 non-null    object
 3   Birthday  450 non-null    datetime64[ns]
 4   Salary    450 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 17.7+ KB

In [126]:
# applying sum()method , using numeric_only parameter set to ture
nba.sum(numeric_only=True)

Salary    3444112694
dtype: int64

In [98]:
nba

               Name                 Team Position  Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG   9/26/96   1445697
1    Christian Wood      Detroit Pistons       PF   9/27/95   1645357
2     PJ Washington    Charlotte Hornets       PF   8/23/98   3831840
3      Derrick Rose      Detroit Pistons       PG   10/4/88   7317074
4     Marial Shayok   Philadelphia 76ers        G   7/26/95     79568
..              ...                  ...      ...       ...       ...
445   Austin Rivers      Houston Rockets       PG    8/1/92   2174310
446     Harry Giles     Sacramento Kings       PF   4/22/98   2578800
447     Robin Lopez      Milwaukee Bucks        C    4/1/88   4767000
448   Collin Sexton  Cleveland Cavaliers       PG    1/4/99   4764960
449     Ricky Rubio         Phoenix Suns       PG  10/21/90  16200000

[450 rows x 5 columns]

In [127]:
nba.sort_values("Name")

                  Name                   Team Position   Birthday    Salary
52        Aaron Gordon          Orlando Magic       PF 1995-09-16  19863636
101      Aaron Holiday         Indiana Pacers       PG 1996-09-30   2239200
437        Abdel Nader  Oklahoma City Thunder       SF 1993-09-25   1618520
81         Adam Mokoka          Chicago Bulls        G 1998-07-18     79568
399  Admiral Schofield     Washington Wizards       SF 1997-03-30   1000000
..                 ...                    ...      ...        ...       ...
159        Zach LaVine          Chicago Bulls       PG 1995-03-10  19500000
302       Zach Norvell     Los Angeles Lakers       SG 1997-12-09     79568
312       Zhaire Smith     Philadelphia 76ers       SG 1999-06-04   3058800
137    Zion Williamson   New Orleans Pelicans        F 2000-07-06   9757440
248     Zylan Cheatham   New Orleans Pelicans       SF 1995-11-17     79568

[450 rows x 5 columns]

In [128]:
nba.sort_values(by="Birthday",ascending=False)

                    Name                  Team Position   Birthday    Salary
136      Sekou Doumbouya       Detroit Pistons       SF 2000-12-23   3285120
432  Talen Horton-Tucker    Los Angeles Lakers       GF 2000-11-25    898310
137      Zion Williamson  New Orleans Pelicans        F 2000-07-06   9757440
313           RJ Barrett       New York Knicks       SG 2000-06-14   7839960
392         Jalen Lecque          Phoenix Suns        G 2000-06-13    898310
..                   ...                   ...      ...        ...       ...
415       Andre Iguodala     Memphis Grizzlies       SF 1984-01-28  17185185
149       Tyson Chandler       Houston Rockets        C 1982-10-02   2564753
262          Kyle Korver       Milwaukee Bucks       PF 1981-03-17   6004753
196        Udonis Haslem            Miami Heat        C 1980-06-09   2564753
98          Vince Carter         Atlanta Hawks       PF 1977-01-26   2564753

[450 rows x 5 columns]

In [100]:
 nba.sort_values("Name" , ascending =False)

                  Name                   Team Position  Birthday    Salary
248     Zylan Cheatham   New Orleans Pelicans       SF  11/17/95     79568
137    Zion Williamson   New Orleans Pelicans        F    7/6/00   9757440
312       Zhaire Smith     Philadelphia 76ers       SG    6/4/99   3058800
302       Zach Norvell     Los Angeles Lakers       SG   12/9/97     79568
159        Zach LaVine          Chicago Bulls       PG   3/10/95  19500000
..                 ...                    ...      ...       ...       ...
399  Admiral Schofield     Washington Wizards       SF   3/30/97   1000000
81         Adam Mokoka          Chicago Bulls        G   7/18/98     79568
437        Abdel Nader  Oklahoma City Thunder       SF   9/25/93   1618520
101      Aaron Holiday         Indiana Pacers       PG   9/30/96   2239200
52        Aaron Gordon          Orlando Magic       PF   9/16/95  19863636

[450 rows x 5 columns]

In [101]:
 nba.sort_values("Birthday" , ascending=False)

                    Name                  Team Position Birthday    Salary
383            Josh Gray  New Orleans Pelicans       PG   9/9/93     79568
310  Matthew Dellavedova   Cleveland Cavaliers       PG   9/8/90   9607500
376     Donovan Mitchell             Utah Jazz       SG   9/7/96   3635760
71            Kevin Love   Cleveland Cavaliers        C   9/7/88  28942830
89            Joe Harris         Brooklyn Nets       SF   9/6/91   7666667
..                   ...                   ...      ...      ...       ...
435         Kadeem Allen       New York Knicks       PG  1/15/93     79568
124          David Nwaba         Brooklyn Nets       SF  1/14/93   1678854
279       Henry Ellenson         Brooklyn Nets       PF  1/13/97     79568
18         Chris Boucher       Toronto Raptors       PF  1/11/93   1588231
160       Tremont Waters        Boston Celtics       PG  1/10/98     79568

[450 rows x 5 columns]

In [102]:
nba.sort_values(by=["Team", "Name"]).head(25) # order of colums is important

                 Name            Team Position  Birthday    Salary
359          Alex Len   Atlanta Hawks        C   6/16/93   4160000
167      Allen Crabbe   Atlanta Hawks       SG    4/9/92  18500000
276   Brandon Goodwin   Atlanta Hawks       PG   10/2/95     79568
438    Bruno Fernando   Atlanta Hawks        C   8/15/98   1400000
194       Cam Reddish   Atlanta Hawks       SF    9/1/99   4245720
111  Chandler Parsons   Atlanta Hawks       SF  10/25/88  25102512
197     Charlie Brown   Atlanta Hawks       SG    2/2/97     79568
130      Damian Jones   Atlanta Hawks        C   6/30/95   2305057
213   De'Andre Hunter   Atlanta Hawks       SF   12/2/97   7068360
28        Evan Turner   Atlanta Hawks       PG  10/27/88  18606556
339     Jabari Parker   Atlanta Hawks       PF   3/15/95   6500000
84       John Collins   Atlanta Hawks       PF   9/23/97   2686560
20      Kevin Huerter   Atlanta Hawks       SG   8/27/98   2636280
290    Tyrone Wallace   Atlanta Hawks       PG   6/10/94   1620564
98       Vince Carter   Atlanta Hawks       PF   1/26/77   2564753
86     Brad Wanamaker  Boston Celtics       PG   7/25/89   1445697
340    Carsen Edwards  Boston Celtics       SG   3/12/98   1228026
189      Daniel Theis  Boston Celtics        C    4/4/92   5000000
419       Enes Kanter  Boston Celtics        C   5/20/92   4767000
199    Gordon Hayward  Boston Celtics       PF   3/23/90  32700690
118    Grant Williams  Boston Celtics       PF  11/30/98   2379840
201     Javonte Green  Boston Celtics       SF   7/23/93    898310
421      Jaylen Brown  Boston Celtics       SF  10/24/96   6534829
398      Jayson Tatum  Boston Celtics       PF    3/3/98   7830000
337      Kemba Walker  Boston Celtics       PG    5/8/90  32742000

In [129]:
nba["Team"]

0       Philadelphia 76ers
1          Detroit Pistons
2        Charlotte Hornets
3          Detroit Pistons
4       Philadelphia 76ers
              ...
445        Houston Rockets
446       Sacramento Kings
447        Milwaukee Bucks
448    Cleveland Cavaliers
449           Phoenix Suns
Name: Team, Length: 450, dtype: object

In [103]:
nba.set_index(keys="Name")
nba.set_index("Name")

                               Team Position  Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG   9/26/96   1445697
Christian Wood      Detroit Pistons       PF   9/27/95   1645357
PJ Washington     Charlotte Hornets       PF   8/23/98   3831840
Derrick Rose        Detroit Pistons       PG   10/4/88   7317074
Marial Shayok    Philadelphia 76ers        G   7/26/95     79568
...                             ...      ...       ...       ...
Austin Rivers       Houston Rockets       PG    8/1/92   2174310
Harry Giles        Sacramento Kings       PF   4/22/98   2578800
Robin Lopez         Milwaukee Bucks        C    4/1/88   4767000
Collin Sexton   Cleveland Cavaliers       PG    1/4/99   4764960
Ricky Rubio            Phoenix Suns       PG  10/21/90  16200000

[450 rows x 4 columns]

In [130]:
nba.sort_values(by=["Team", "Name"], ascending=False)

                Name                Team Position   Birthday    Salary
36     Thomas Bryant  Washington Wizards        C 1997-07-31   8000000
21     Rui Hachimura  Washington Wizards       PF 1998-02-08   4469160
428    Moritz Wagner  Washington Wizards        C 1997-04-26   2063520
273  Justin Robinson  Washington Wizards       PG 1997-10-12    898310
418     Jordan McRae  Washington Wizards       PG 1991-03-28   1645357
..               ...                 ...      ...        ...       ...
194      Cam Reddish       Atlanta Hawks       SF 1999-09-01   4245720
438   Bruno Fernando       Atlanta Hawks        C 1998-08-15   1400000
276  Brandon Goodwin       Atlanta Hawks       PG 1995-10-02     79568
167     Allen Crabbe       Atlanta Hawks       SG 1992-04-09  18500000
359         Alex Len       Atlanta Hawks        C 1993-06-16   4160000

[450 rows x 5 columns]

In [131]:
nba.select_dtypes(include="object").head(3)

             Name                Team Position
0    Shake Milton  Philadelphia 76ers       SG
1  Christian Wood     Detroit Pistons       PF
2   PJ Washington   Charlotte Hornets       PF

In [132]:
nba.sort_values(by=["Team", "Name"], ascending=[True,False]).head(25)

                 Name            Team Position   Birthday    Salary
98       Vince Carter   Atlanta Hawks       PF 1977-01-26   2564753
290    Tyrone Wallace   Atlanta Hawks       PG 1994-06-10   1620564
20      Kevin Huerter   Atlanta Hawks       SG 1998-08-27   2636280
84       John Collins   Atlanta Hawks       PF 1997-09-23   2686560
339     Jabari Parker   Atlanta Hawks       PF 1995-03-15   6500000
28        Evan Turner   Atlanta Hawks       PG 1988-10-27  18606556
213   De'Andre Hunter   Atlanta Hawks       SF 1997-12-02   7068360
130      Damian Jones   Atlanta Hawks        C 1995-06-30   2305057
197     Charlie Brown   Atlanta Hawks       SG 1997-02-02     79568
111  Chandler Parsons   Atlanta Hawks       SF 1988-10-25  25102512
194       Cam Reddish   Atlanta Hawks       SF 1999-09-01   4245720
438    Bruno Fernando   Atlanta Hawks        C 1998-08-15   1400000
276   Brandon Goodwin   Atlanta Hawks       PG 1995-10-02     79568
167      Allen Crabbe   Atlanta Hawks       SG 1992-04-09  18500000
359          Alex Len   Atlanta Hawks        C 1993-06-16   4160000
416   Vincent Poirier  Boston Celtics        C 1993-10-17   2505793
160    Tremont Waters  Boston Celtics       PG 1998-01-10     79568
395        Tacko Fall  Boston Celtics        C 1995-12-10     79568
425      Semi Ojeleye  Boston Celtics       PF 1994-12-05   1618520
405    Romeo Langford  Boston Celtics       SG 1999-10-25   3458400
59       Marcus Smart  Boston Celtics       PG 1994-03-06  12553571
337      Kemba Walker  Boston Celtics       PG 1990-05-08  32742000
398      Jayson Tatum  Boston Celtics       PF 1998-03-03   7830000
421      Jaylen Brown  Boston Celtics       SF 1996-10-24   6534829
201     Javonte Green  Boston Celtics       SF 1993-07-23    898310

In [133]:
nba.sort_index(axis=1).head(4) # OR
nba.sort_index(axis="columns").head(4)

    Birthday            Name Position   Salary                Team
0 1996-09-26    Shake Milton       SG  1445697  Philadelphia 76ers
1 1995-09-27  Christian Wood       PF  1645357     Detroit Pistons
2 1998-08-23   PJ Washington       PF  3831840   Charlotte Hornets
3 1988-10-04    Derrick Rose       PG  7317074     Detroit Pistons

In [134]:
nba.sort_index(axis=1, ascending=False).head(4)

                 Team   Salary Position            Name   Birthday
0  Philadelphia 76ers  1445697       SG    Shake Milton 1996-09-26
1     Detroit Pistons  1645357       PF  Christian Wood 1995-09-27
2   Charlotte Hornets  3831840       PF   PJ Washington 1998-08-23
3     Detroit Pistons  7317074       PG    Derrick Rose 1988-10-04

In [135]:
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

### SETTING NEW INDEX

In [109]:
nba.set_index(keys="Name")
nba.set_index("Name")

                               Team Position  Birthday    Salary
Name
Shake Milton     Philadelphia 76ers       SG   9/26/96   1445697
Christian Wood      Detroit Pistons       PF   9/27/95   1645357
PJ Washington     Charlotte Hornets       PF   8/23/98   3831840
Derrick Rose        Detroit Pistons       PG   10/4/88   7317074
Marial Shayok    Philadelphia 76ers        G   7/26/95     79568
...                             ...      ...       ...       ...
Austin Rivers       Houston Rockets       PG    8/1/92   2174310
Harry Giles        Sacramento Kings       PF   4/22/98   2578800
Robin Lopez         Milwaukee Bucks        C    4/1/88   4767000
Collin Sexton   Cleveland Cavaliers       PG    1/4/99   4764960
Ricky Rubio            Phoenix Suns       PG  10/21/90  16200000

[450 rows x 4 columns]

In [136]:
nba.select_dtypes(exclude=["object","int"]).head(3)

    Birthday
0 1996-09-26
1 1995-09-27
2 1998-08-23

In [138]:
nba.loc["PJ Washington"]

KeyError: 'PJ Washington'

In [139]:
nba[["Team", "Salary"]].head(3)

                 Team   Salary
0  Philadelphia 76ers  1445697
1     Detroit Pistons  1645357
2   Charlotte Hornets  3831840

In [140]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      450 non-null    object
 1   Team      450 non-null    object
 2   Position  450 non-null    object
 3   Birthday  450 non-null    datetime64[ns]
 4   Salary    450 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 17.7+ KB

In [141]:
nba.select_dtypes(include="object").head(3)

             Name                Team Position
0    Shake Milton  Philadelphia 76ers       SG
1  Christian Wood     Detroit Pistons       PF
2   PJ Washington   Charlotte Hornets       PF

In [142]:
nba.select_dtypes(exclude=["object" , "int"]).head(3)

    Birthday
0 1996-09-26
1 1995-09-27
2 1998-08-23

In [143]:
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450 entries, 0 to 449
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      450 non-null    object
 1   Team      450 non-null    object
 2   Position  450 non-null    object
 3   Birthday  450 non-null    datetime64[ns]
 4   Salary    450 non-null    int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 17.7+ KB

In [144]:
nba.select_dtypes(include="object").head(3)

             Name                Team Position
0    Shake Milton  Philadelphia 76ers       SG
1  Christian Wood     Detroit Pistons       PF
2   PJ Washington   Charlotte Hornets       PF

#### loc[] - loc stand for location

In [145]:
nba.select_dtypes(exclude=["object","int"]).head(3)

    Birthday
0 1996-09-26
1 1995-09-27
2 1998-08-23

In [146]:
nba

               Name                 Team Position   Birthday    Salary
0      Shake Milton   Philadelphia 76ers       SG 1996-09-26   1445697
1    Christian Wood      Detroit Pistons       PF 1995-09-27   1645357
2     PJ Washington    Charlotte Hornets       PF 1998-08-23   3831840
3      Derrick Rose      Detroit Pistons       PG 1988-10-04   7317074
4     Marial Shayok   Philadelphia 76ers        G 1995-07-26     79568
..              ...                  ...      ...        ...       ...
445   Austin Rivers      Houston Rockets       PG 1992-08-01   2174310
446     Harry Giles     Sacramento Kings       PF 1998-04-22   2578800
447     Robin Lopez      Milwaukee Bucks        C 1988-04-01   4767000
448   Collin Sexton  Cleveland Cavaliers       PG 1999-01-04   4764960
449     Ricky Rubio         Phoenix Suns       PG 1990-10-21  16200000

[450 rows x 5 columns]

In [149]:
nba.loc["PJ Washington"]

KeyError: 'PJ Washington'